---
- name: Create environment for server 4
  hosts: server-4
  become: true
  gather_facts: false
  vars:
    pass_auth: "no"
    allow_ssh_user: "AllowUsers service_user, vagrant"
  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        # password: pass
        password: $1$salt$M6xQvx9eSlM4zTu69di5B/
        shell: /bin/bash
        createhome: yes
        # group: wheel
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      with_items:
          - service_user
          - user2

    - name: Change ssh config
      template:
        src: ./templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
      notify: reload ssh

    - name: set authorized_key for service_user
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'files/my_user2.pub') }}"
        exclusive: yes
      with_items:
        - service_user
        - user2

  handlers:
    - name: reload ssh
      systemd: name=sshd state=restarted

