---
- name: Create environment for server 5
  hosts: server-5
  become: true
  gather_facts: false
  vars:
    pass_auth: "yes"
    allow_ssh_user: "AllowUsers service_user user1 vagrant"
  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        # password: pass
        password: $1$nmVTz36m$izByePox9z0xkP8ybQPtD1
        shell: /bin/bash
        createhome: yes
        # group: wheel
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      with_items:
        - service_user
        - user1
        - user2

    - name: Change ssh config
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
      notify: reload ssh

    - name: set authorized_key for users
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('pipe', 'cat files/*.pub') }}"
      with_items:
        - service_user
        - user1
        - user2

  handlers:
    - name: reload ssh
      systemd: name=sshd state=restarted
